%step 1: import data 
%import data from txt file generated by the NI signal express

%step 2: analysis data

vel_data = data(:,1);
pos_data = data(:,2);
data_len = length(vel_data);
sampleRate = 1000;

% convert position data (AO) to velocity data
%uw_pos2=(max(pos_data)/(2*pi))*unwrap(pos_data*(2*pi/max(pos_data)));
%vel_from_pos = vel_estimate(uw_pos2, 1/sampleRate, 'line_fit',  500, []);

kk=diff(pos_data);
aa=find(kk<-4);

for i = 1:length(aa)
    bb(i)=pos_data(aa(i));
end;

for i=1:length(aa)
    pos_data(aa(i)+1 : end) = pos_data(aa(i)+1 : end) + bb(i);
end
    
% vel_from_pos = diff(pos_data)*1000;
% vel_from_pos =[vel_from_pos(1); vel_from_pos];

vel_from_pos = vel_estimate(pos_data, 1/sampleRate, 'lpfilt', [], 2);
%normalize analog input data
vel_data = vel_data - min(vel_data);
input = vel_data/max(vel_data);

%normalize analog output data
vel_from_pos = vel_from_pos - min(vel_from_pos);
output = vel_from_pos/max(vel_from_pos);

subplot(2,1,1);
plot(input)
hold on
plot(output,'r');
title('signals')

% calculate the cross correlation 
x1 = xcorr(input', output', 'coeff');
tx1 = [(1-data_len):(data_len -1)]/sampleRate;

subplot(2,1,2)
plot(tx1,x1)

% find the delay
[mx1,ix1] = max(x1);
lag1 = tx1(ix1)
hold on
tm1=[lag1,lag1];
mm = [0,1];
plot(tm1,mm,'k')
S = sprintf('Lag = %5.2f',lag1);
title(S)
